[programs.localnet]
anchor_escrow = "AATdQpopjKABYHXMthLY7HCjpFHeDLUw6cgAK2rwD7vY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/wallywilliams/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
